### ISSUE TITLE
Hungrymark doesn't show the popup list when I use multiple displays

### ISSUE THREAD

**Issue by Emrys365** [zhengying/Hungrymark-issue#21] opened 2020-11-09 11:31 UTC
When I use my macbook with an external display, I found that Hungrymark `Version 1.2.7 (20)` could not show its popup list when I clicked on the icon in one of the displays. Below is an example:

### On the built-in Retina display
![builtin display](https://user-images.githubusercontent.com/18532145/98535888-d4d9ad00-22c1-11eb-9296-04924c287a35.gif)

### On the external display
![external display](https://user-images.githubusercontent.com/18532145/98535924-e0c56f00-22c1-11eb-92e8-ec6bfd11ef29.gif)

I'm not sure if anyone else also has this problem?

**Comment by zhengying** [comment] 2020-12-22 01:09
Hi.thanks for your report.
But I can't reproduce on all my device.
What's your macOS version?

the new 1.3.0 already released, can you test it again? if any problem, please let me know.

**Comment by Emrys365** [comment] 2020-12-22 02:34
I'm using macOS 10.15.7.
Now I've tried the latest version. But the problem still remains.
![builtinDisplay](https://user-images.githubusercontent.com/18532145/102842023-03aa7d80-4441-11eb-984a-9ae9aa412bd0.gif)
![extDisplay](https://user-images.githubusercontent.com/18532145/102842040-0c02b880-4441-11eb-9f14-63898eb951ce.gif)

**Comment by zhengying** [comment] 2020-12-22 02:57
Thanks for your test,  
I will investigate this bug as soon as possible.

**Comment by zhengying** [comment] 2020-12-23 02:39
> I'm using macOS 10.15.7.
> Now I've tried the latest version. But the problem still remains.
> ![builtinDisplay](https://user-images.githubusercontent.com/18532145/102842023-03aa7d80-4441-11eb-984a-9ae9aa412bd0.gif)
> ![extDisplay](https://user-images.githubusercontent.com/18532145/102842040-0c02b880-4441-11eb-9f14-63898eb951ce.gif)

hi @Emrys365 

I can't reproduce this bug, 
I think it may be caused by a bug in macOS API,
 I have built a new version with another PopupMenu API, but I can't test it.
Can you test it for me?
 
I shared the version with a dropbox link:
[Version link](https://www.dropbox.com/sh/idpuxb82faojm6g/AAA0IUa0YXHzEuw7T6UMIzWka?dl=0)
if you can't open it in your Mac, you can use  cmd: 
xattr -rd com.apple.quarantine  [your path]/Hungrymark.app

Thanks.

**Comment by Emrys365** [comment] 2020-12-23 05:22
> hi @Emrys365
> 
> I can't reproduce this bug,
> I think it may be caused by a bug in macOS API,
> I have built a new version with another PopupMenu API, but I can't test it.
> Can you test it for me?
> 
> I shared the version with a dropbox link:
> [Version link](https://www.dropbox.com/sh/idpuxb82faojm6g/AAA0IUa0YXHzEuw7T6UMIzWka?dl=0)
> if you can't open it in your Mac, you can use cmd:
> xattr -rd com.apple.quarantine [your path]/Hungrymark.app
> 
> Thanks.

Many thanks! I just test it and it works! Now everything is working well! 👍

**Comment by zhengying** [comment] 2020-12-23 05:51
> > xattr -rd com.apple.quarantine [your path]/Hungrymark.app
> > Thanks.
> 
> Many thanks! I just test it and it works! Now everything is working well! 👍

Thanks for your testing! I will release it in next version.
Any problem, please contact me.

**Comment by zhengying** [comment] 2021-01-10 13:58
fixed in 1.3.2.28

**Closed as completed by zhengying** 2021-01-10 13:58 UTC
